author: Morgan Sadr-Hashemi
title: Morgan's blog
description: >-
  Development Team Lead at Nested. I like tech, gym and food.
baseurl: ""
url: "https://sadir.github.io/"

logo: "/assets/images/logo.png"
menu:
  - href: "/about"
    text: About
  - href: "/cv"
    text: CV
  - href: "/posts"
    text: Posts
  - href: "https://github.com/sadir/sadir-jekyll"
    text: Get this theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

paginate: 2
paginate_path: "/posts/:num/"

twitter_url: https://twitter.com/sadir_
linkedin_url: https://www.linkedin.com/in/morgan-sadr-hashemi/
github_url: https://github.com/sadir
rss_feed: true

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
