defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      logo: "/assets/images/logo.png"
      menu:
        - href: "https://twitter.com/sadir_"
          text: twitter
        - href: "https://www.linkedin.com/in/morgan-sadr-hashemi/"
          text: linkedin
        - href: "https://github.com/sadir"
          text: github

twitter_url: https://twitter.com/sadir_
linkedin_url: https://www.linkedin.com/in/morgan-sadr-hashemi/
github_url: https://github.com/sadir
rss_feed: true
